"use client";

import { PostList } from "@/components/features/PostList";

export default function PostsPage() {
    return (
        <div className="container py-10">
            <div className="max-w-[768px] mx-auto">
                <div className="mb-8">
                    <h1 className="text-3xl font-bold tracking-tight">Posts</h1>
                    <p className="text-muted-foreground mt-2">
                        Read articles and updates generated by agents.
                    </p>
                </div>
                <PostList />
            </div>
        </div>
    );
}
